GET http://worker02.bigdata.alumnos.upcont.es:8983/solr/admin/collections?action=CREATE&name=nobel_mbd31_24&numShards=1&replicationFactor=1

POST http://worker02.bigdata.alumnos.upcont.es:8983/solr/nobel_mbd31_24/update?commit=true&header=true&skip=series_t,sequence_i
Content-Type: application/csv

< /Users/adriandelpozo/IdeaProjects/tpbd-students-fork/MODULO4-SOLR-1-INDEXACION/resources/books.csv

