{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "59ecb486-eb55-47e7-94c4-4354b1e431dd",
   "metadata": {},
   "source": [
    "# PRÁCTICA 7: SPIDER NIVEL 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "f2afc949-43b8-4994-be09-08ebbc9b4ebb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import csv\n",
    "from urllib.parse import unquote"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "81d53973-e8e6-46b6-830b-ca90bfbab429",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://en.wikipedia.org/wiki/List_of_universities_in_Algeria\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Angola\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Benin\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Botswana\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Burkina_Faso\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Burundi\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Cameroon\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Cape_Verde\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Central_African_Republic\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Chad\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Comoros\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Republic_of_the_Congo\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Democratic_Republic_of_the_Congo\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Djibouti\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Egypt\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Eritrea\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Ethiopia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Equatorial_Guinea\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Eswatini\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Gabon\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Gambia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Ghana\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Guinea\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Guinea-Bissau\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Ivory_Coast\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Kenya\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Lesotho\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Liberia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Libya\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Madagascar\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Malawi\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Mali\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Mauritania\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Mauritius\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Morocco\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Mozambique\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Namibia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Niger\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Nigeria\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Rwanda\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Senegal\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Seychelles\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Sierra_Leone\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Somalia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Somaliland\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_South_Sudan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Sudan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_South_Africa\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Tanzania\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Togo\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Tunisia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Uganda\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Zambia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Zimbabwe\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Antigua_and_Barbuda\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Argentina\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Bahamas\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Barbados\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Belize\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Bolivia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Brazil_by_state\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Canada\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Cayman_Islands\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Chile\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Colombia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Costa_Rica\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Cuba\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Dominica\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Dominican_Republic\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Ecuador\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_El_Salvador\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Grenada\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Guatemala\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Guyana\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Haiti\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Honduras\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Jamaica\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Mexico\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Nicaragua\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Panama\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Paraguay\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Peru\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Saint_Kitts_and_Nevis\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Saint_Vincent_and_the_Grenadines\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Trinidad_and_Tobago\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Uruguay\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Venezuela\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Afghanistan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Bahrain\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Bangladesh\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Bhutan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Brunei\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Cambodia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_China\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_East_Timor\n",
      "https://en.wikipedia.org/wiki/List_of_higher_education_institutions_in_Hong_Kong\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_India\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Indonesia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Iran\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Iraq\n",
      "https://en.wikipedia.org/wiki/List_of_Israeli_universities_and_colleges\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Japan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Jordan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Kazakhstan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Kuwait\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Kyrgyzstan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Laos\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Lebanon\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Malaysia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Macau\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Mongolia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Myanmar\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Nepal\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_North_Korea\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Oman\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Pakistan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Palestine\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_the_Philippines\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Qatar\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Saudi_Arabia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Singapore\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_South_Korea\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Sri_Lanka\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Syria\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Taiwan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Tajikistan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Thailand\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Turkmenistan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_the_United_Arab_Emirates\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Uzbekistan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Vietnam\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Yemen\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Albania\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Armenia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Austria\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Azerbaijan\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Belarus\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Belgium\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Bosnia_and_Herzegovina\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Bulgaria\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Croatia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Cyprus\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Czech_Republic\n",
      "https://en.wikipedia.org/wiki/List_of_educational_institutions_in_Denmark\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Greenland\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Estonia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Finland\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_France\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Georgia_(country)\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Germany\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Greece\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Hungary\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Iceland\n",
      "https://en.wikipedia.org/wiki/Third-level_education_in_the_Republic_of_Ireland#List_of_higher_education_establishments\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Italy\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Kosovo\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Latvia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Liechtenstein\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Lithuania\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Malta\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Moldova\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Montenegro\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Netherlands\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Northern_Cyprus\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_North_Macedonia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Norway\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Poland\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Portugal\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Romania\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Russia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_San_Marino\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Serbia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Slovakia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Slovenia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Spain\n",
      "https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Sweden\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Switzerland\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Turkey\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Ukraine\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_United_Kingdom\n",
      "https://en.wikipedia.org/wiki/List_of_colleges_in_the_United_Kingdom_offering_higher_education_courses\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_England\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Northern_Ireland\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Scotland\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Wales\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_the_Vatican_City\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Australia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Cook_Islands\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Melanesia#Fiji\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#French_Polynesia\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_New_Zealand\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Nauru\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Niue\n",
      "https://en.wikipedia.org/wiki/List_of_schools_in_Papua_New_Guinea#Universities_and_tertiary_education\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Samoa\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Melanesia#Solomon_Islands\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Tokelau\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Tonga\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Tuvalu\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Melanesia#Vanuatu\n",
      "https://en.wikipedia.org/wiki/List_of_universities_in_Polynesia#Wallis_and_Futuna\n"
     ]
    }
   ],
   "source": [
    "# Guardamos en la variable URL la dirección de la página web donde están listadas las universidades y colegios por país.\n",
    "url = \"https://en.wikipedia.org/wiki/Lists_of_universities_and_colleges_by_country\"\n",
    "\n",
    "# Realizamos una solicitud para obtener el contenido de la página web. \n",
    "# Básicamente, le pedimos al servidor que nos envíe el HTML completo de la página que hemos indicado.\n",
    "response = requests.get(url)\n",
    "\n",
    "# Procesamos el contenido HTML recibido utilizando BeautifulSoup.\n",
    "# Lo que nos permite es convertir el texto HTML en un objeto que podemos analizar y manipular fácilmente.\n",
    "soup = BeautifulSoup(response.content, \"html.parser\")\n",
    "\n",
    "\n",
    "# Extraemos todos los elementos <a> de la página, que son los enlaces.\n",
    "# Estos elementos contienen atributos 'href' que apuntan a otras páginas web.\n",
    "links = soup.find_all('a', href=True)\n",
    "\n",
    "# Filtramos los enlaces que contienen una lista de las universidades de cada país. Al explorar la url \n",
    "# https://en.wikipedia.org/wiki/Lists_of_universities_and_colleges_by_country vemos que todas las direcciones que buscamos contienen \n",
    "# la cadena \"List_of_universities\" o \"List_of_colleges\" o \"List_of_schools\". Se muestra un ejemplo de cada uno de los casos anteriores\n",
    "# a continuación:\n",
    "# https://en.wikipedia.org/wiki/List_of_universities_in_Ghana\n",
    "# https://en.wikipedia.org/wiki/List_of_colleges_in_the_United_Kingdom_offering_higher_education_courses\n",
    "# https://en.wikipedia.org/wiki/List_of_schools_in_Papua_New_Guinea#Universities_and_tertiary_education\n",
    "# En definitiva, buscamos los urls con que contengan el \n",
    "# patrón \"List_of\". Sin embargo, hay un enlaces que no contienen este patrón: el relativo a las Faroe Islands \n",
    "# (https://en.wikipedia.org/wiki/Education_in_the_Faroe_Islands#Higher_education) . Se decide no incluirlo ya que \n",
    "# el enlace no contiene una lista de universidades como tal, si no una historia de la Educación en las Islas Feroe.\n",
    "country_links = [link['href'] for link in links if 'List_of' in link['href']]\n",
    "\n",
    "\n",
    "# Eliminamos los últimos 11 enlaces de la lista porque no corresponde a un país, sino a enlaces que contienen información sobre International\n",
    "# schools, listas de universidades medievales o fundadas en Europa a partir de 1945. Es decir, información que no necesitamos para nuestro \n",
    "# propósito.\n",
    "country_links = country_links[:-11]\n",
    "\n",
    "# Iteramos sobre cada enlace filtrado y completamos la URL base para que los enlaces sean accesibles directamente.\n",
    "# Mostramos estas URLs completas, añadiendo 'https://en.wikipedia.org' al inicio, ya que los enlaces originales son relativos.\n",
    "\n",
    "for link in country_links:\n",
    "    print(f\"https://en.wikipedia.org{link}\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "4b567e2d-ec0c-4157-81de-328cbeef4cf2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Archivo countries.csv creado con éxito.\n"
     ]
    }
   ],
   "source": [
    "# Extraemos el nombre del país a partir de la estructura del enlace\n",
    "country_data = []\n",
    "# Creamos una lista vacía donde guardaremos los nombres de los países y sus enlaces.\n",
    "\n",
    "for href in country_links:\n",
    "    if \"List_of\" in href:  # Verificamos que el patrón exista\n",
    "        # Recorremos cada enlace filtrado previamente y verificamos que siga el patrón que identifica a un país.\n",
    "        \n",
    "        # Decodificamos los caracteres especiales del enlace (como espacios o acentos, eg. São Tomé, etc.) para facilitar su manipulación.\n",
    "        decoded_href = unquote(href)\n",
    "\n",
    "        # Todos los enlaces contienen el nombre del país tras la palabra \"in\", por lo que nos aprovechamos de ese patrón para \n",
    "        # obtener el nombre del país. Los casos especiales se tratarán más abajo.\n",
    "        if \"in_\" in decoded_href:\n",
    "            country_name = decoded_href.split(\"_in_\")[1]        \n",
    "\n",
    "        # Reemplazamos los guiones bajos por espacios y ajustamos el formato del texto, \n",
    "        # convirtiendo las palabras a formato título (cada palabra comienza con mayúscula).\n",
    "        country_name = country_name.replace(\"_\", \" \").strip().title()\n",
    "\n",
    "\n",
    "        #Hay tres casos especiales en los datos que debemos tratar individualmente.\n",
    "        #1.- El enlace de The Republic of Ireland es:\n",
    "        #    https://en.wikipedia.org/wiki/Third-level_education_in_the_Republic_of_Ireland#List_of_higher_education_establishments \n",
    "        #    Como vemos, después del nombre del país tiene la cadena #List of higher education establishments, que debemos eliminar \n",
    "        #    del nombre del pais.\n",
    "        if \"Third-level_education_in_the_Republic_of_Ireland\" in decoded_href:\n",
    "            country_name = \"The Republic Of Ireland\"\n",
    "\n",
    "        #2.- United Kingdom tiene un enlace con la lista de universities y otra con la lista de colleges. En este segundo caso, la URL es\n",
    "        #    https://en.wikipedia.org/wiki/List_of_colleges_in_the_United_Kingdom_offering_higher_education_courses. Vamos a sustituir\n",
    "        #    The United Kingdom offering higher education courses, que es lo que tenemos ahora mismo, por The United Kingdom (colleges).\n",
    "        if \"List_of_colleges_in_the_United_Kingdom_offering_higher_education_courses\" in decoded_href:\n",
    "            country_name = \"The United Kingdom (Colleges)\"\n",
    "\n",
    "\n",
    "        #3.- El URL relativo a Papua New Guinea es:\n",
    "        #    https://en.wikipedia.org/wiki/List_of_schools_in_Papua_New_Guinea#Universities_and_tertiary_education\n",
    "        #    Ahora mismo tenemos Papua New Guinea#Universities and tertiary education, y queremos que ponga simplemente Papua New Guinea.\n",
    "        if \"List_of_schools_in_Papua_New_Guinea\" in decoded_href:\n",
    "            country_name = \"Papua New Guinea\"\n",
    "\n",
    "        \n",
    "        # 4.- Algunos de los países contienen una almohadilla en el nombre, por ejemplo Polynesia#Wallis_and_Futuna. Vamos a sustituir  la \n",
    "        #     almohadilla por \":\" :\n",
    "        if \"#\" in country_name:\n",
    "            country_name = country_name.replace(\"#\", \": \")\n",
    "\n",
    "        \n",
    "        # Guardamos el nombre del país y el enlace correspondiente en nuestra lista.\n",
    "        country_data.append((country_name, decoded_href))\n",
    "        \n",
    "\n",
    "# Escribimos los resultados en un archivo CSV\n",
    "with open(\"countries.csv\", \"w\", newline=\"\", encoding=\"utf-8\") as csvfile:\n",
    "    # Abrimos un archivo llamado \"countries.csv\" en modo escritura. \n",
    "    # Configuramos el delimitador como punto y coma para separar los valores.\n",
    "    writer = csv.writer(csvfile, delimiter=';')\n",
    "   \n",
    "\n",
    "    # Añadimos la primera fila al archivo, que contiene los nombres de las columnas: \n",
    "    # el nombre del país y la URL completa.    \n",
    "    writer.writerow([\"CountryName\", \"CountryUrl\"])\n",
    "   \n",
    "\n",
    "    # Escribimos los datos de cada país\n",
    "    for name, href in country_data:\n",
    "        # Recorremos nuestra lista de países y, para cada uno, escribimos su nombre y su enlace completo.\n",
    "        # Añadimos la base 'https://en.wikipedia.org' para completar las URLs relativas.\n",
    "        writer.writerow([name, f\"https://en.wikipedia.org{href}\"])\n",
    "        \n",
    "# Mostramos un mensaje para indicar que hemos generado el archivo CSV con los datos procesados.\n",
    "print(\"Archivo countries.csv creado con éxito.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
